name: Build Firmware (PR) on ht-hd01-v2

permissions:
  contents: read

on:
  pull_request:
    paths:
    - 'boards/ht-hd01-v2/**'
    - 'boards/common_extras/**'
    - 'include/kernel*'
    - 'package/kernel/**'
    - 'package/firmware/**'
    - 'target/linux/ramips/**'
    - 'feeds.conf.default'

jobs:
  build-hd01-v2:
    name: Build HD01 V2
    uses: ./.github/workflows/build-firmware.yml
    with:
      board: ht-hd01-v2
      target: ramips
      subtarget: mt76x8
      description: "Heltec HT-HD01 V2 (MT76x8)"
